# Change these first
owner: j-ranck-electric # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: jranck.com
    url: https://jranck.com
  - name: Spectrum Web App
    url: https://jranck.dexterchaney.com
  - name: JRE Documentation
    url: https://docs.jranck.com
  - name: Fore the Kids
    url: https://forethekids.jranck.com
  - name: HR App
    url: https://hr.jranck.com
  - name: Onboarding App
    url: https://onboarding.jranck.com
  - name: Operations App
    url: https://operations.jranck.com
  - name: PTE App
    url: https://pte.jranck.com
  - name: Safety App
    url: https://safety.jranck.com
  - name: Warehouse App
    url: https://warehouse.jranck.com
  - name: Solar Safety Trainings
    url: https://glstc.jranck.com
  - name: JRE Store
    url: https://store.jranck.com
  - name: app.jranck.com
    url: https://app.jranck.com
  - name: API
    url: https://api.jranck.com/permissions/anontest

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jranck.com
  # baseUrl: /upptime
  logoUrl: https://jreappstorage.blob.core.windows.net/public/JRE_white.png
  name: JRE Service Status
  # introTitle: "**Upptime** is the open-source upptime monitor and status page, powered entirely by GitHub."
  # introMessage: No server required — just GitHub Actions, Issues, and Pages
  theme: dark
  robotsText: "User-agent: * \n Disallow: /"
  css: ".logo > img { height: 30px !important; }"
  # navbar:
  #   - title: Status
  #     href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
